from enum import Enum

class StatusConferencia(str, Enum):
    RASCUNHO = "RASCUNHO"
    EM_CONFERENCIA = "EM_CONFERENCIA"
    FINALIZADA = "FINALIZADA"
    EM_AUDITORIA = "EM_AUDITORIA"
    APROVADA = "APROVADA"
    REPROVADA = "REPROVADA"
    REABERTA = "REABERTA"


class TipoDivergencia(str, Enum):
    QUANTIDADE_MENOR = "QUANTIDADE_MENOR"
    QUANTIDADE_MAIOR = "QUANTIDADE_MAIOR"
    PRODUTO_NAO_ENCONTRADO = "PRODUTO_NAO_ENCONTRADO"
    PRODUTO_A_MAIS = "PRODUTO_A_MAIS"
    CODIGO_DIVERGENTE = "CODIGO_DIVERGENTE"


class StatusItem(str, Enum):
    NAO_CONFERIDO = "NAO_CONFERIDO"
    OK = "OK"
    DIVERGENTE = "DIVERGENTE"
    JUSTIFICADO = "JUSTIFICADO"


class TipoJustificativa(str, Enum):
    ERRO_FORNECEDOR = "ERRO_FORNECEDOR"
    ERRO_CONFERENCIA = "ERRO_CONFERENCIA"
    ERRO_CADASTRO = "ERRO_CADASTRO"
    OUTROS = "OUTROS"