
# CONFERENCIA

STATUS_ABERTA = "ABERTA"
STATUS_FINALIZADA = "FINALIZADA"
STATUS_REABERTA = "REABERTA"
STATUS_APROVADA = "APROVADA"
STATUS_REPROVADA = "REPROVADA"


# DIVERGENCIA

DIVERGENCIA_PENDENTE = "PENDENTE"
DIVERGENCIA_JUSTIFICADA = "JUSTIFICADA"
DIVERGENCIA_VALIDADA = "VALIDADA"


# ITENS

ITEM_NAO_CONFERIDO = "NAO_CONFERIDO"
ITEM_OK = "OK"
ITEM_DIVERGENTE = "DIVERGENTE"